-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 10.11.255.88
-- Tiempo de generación: 06-11-2023 a las 18:17:04
-- Versión del servidor: 10.3.28-MariaDB
-- Versión de PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `plantilla`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `profesiones`
--

CREATE TABLE `profesiones` (
  `id` int(11) NOT NULL,
  `disiplina` varchar(250) COLLATE utf8_spanish_ci DEFAULT NULL,
  `nombre_profesion` varchar(500) COLLATE utf8_spanish_ci DEFAULT NULL,
  `cantidad_CV` int(11) DEFAULT NULL,
  `actividad_realizar` varchar(5000) COLLATE utf8_spanish_ci DEFAULT NULL,
  `requerimientos_observaciones` varchar(5000) COLLATE utf8_spanish_ci DEFAULT NULL,
  `id_proyecto` int(11) NOT NULL,
  `status` tinyint(2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `profesiones`
--

INSERT INTO `profesiones` (`id`, `disiplina`, `nombre_profesion`, `cantidad_CV`, `actividad_realizar`, `requerimientos_observaciones`, `id_proyecto`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Artista visual', 'Diseñadores(as), ilustradores(as), fotógrafos(as) y creadores(as) visuales.', 10, 'Elaboración de una serie de 2 carteles y 2 infografías sobre las medidas de Sana Distancia y temas alusivos a la situación actual derivada de la pandemia por COVID-19; los cuales se colocarán en espacios comunes de Unidades Habitacionales de la CDMX y se distribuirán como contenidos digitales en redes sociales. Las propuestas de cartel e infografía pueden desarrollarse en las siguientes expresiones visuales: Ilustración, collage, dibujo digital, fotografía, gráfica, narrativa gráfica, pintura, dibujo y diseño gráfico. Los carteles deben entregarse en archivo digital de 300 dpi o ser elementos vectoriales, adecuados a las dimensiones o tamaño del cartel (70x100 cm, 50x70 cm y/o 35x50 cm) y debe incluir, sin excepción, los archivos de las tipografías empleadas. Las infografías deben entregarse en archivo digital en formatos: jpg, png o gif.  Imágenes de tamaño 1080 px de su lado más corto, para ser publicadas en redes sociales.  En caso de utilizarlas, es necesario que tanto infografías como carteles integren las referencias de las fuentes de información y/o de datos que utilicen.  Realizará las correcciones pertinentes que se indiquen a los materiales solicitados en tiempo y forma de acuerdo con las fechas de entrega que se indiquen.', 'La participación podrá solicitarse tanto para trabajar de manera individidual como colectiva. Trayectoria de tres o más años en creación visual ya sea de manera individual o como colectivo.  Contar con equipo, materiales y medios para elaborar y entregar los materiales requeridos.  Los contenidos deben responder a los principios de respeto y no discriminación.  La obra debe ser inédita y no haber sido publicada previamente en cualquier medio y/o convocatorias. Los productos visuales serán utilizados por la Secretaría de Cultura del Gobierno de México para todos los contenidos que se requiera y considere pertinente. Se deberá firmar una carta de cesión de derechos para la publicación y manipulación de las imágenes de los productos visuales que se entreguen.', 1, 1, NULL, NULL),
(2, 'Fotografía', 'Fotógrafos(as)', 10, 'Realizará el registro fotográfico de actividades culturales en Unidades Habitacionales de la CDMX: desde el montaje hasta el desmontaje de las mismas. Entregará material fotográfico previamente editado. Realizará las correcciones pertinentes que se indiquen a los materiales solicitados en tiempo y forma de acuerdo con las fechas de entrega que se indiquen.', 'Facilidad para trasladarse y transportar el equipamiento técnico Experiencia mínima de tres años en registro fotográfico y edición de imágenes Contar con equipo básico de fotografía propio: cámara fotográfica, Tripie Flash. Equipo de cómputo con softwares de edición de fotografía En caso de no contar con equipo propio puede ser subarrendado por el/la fotógrafo(a) Los productos visuales serán utilizados por la Secretaría de Cultura del Gobierno de México para todos los contenidos que se requiera y considere pertinente. Se deberá firmar una carta de cesión de derechos para la publicación y manipulación de las imágenes de los productos visuales que se entreguen.', 1, 1, NULL, NULL),
(3, 'Narración oral y lectura en voz alta', 'Narradores orales, lectores en voz alta', 50, 'Cuento al pie de tu ventana. Se realizarán narraciones orales, lecturas en voz alta, propuestas interdisciplinarias (música y narración), lecturas dramatizada y/o caracterizadas en Unidades Habitacionales de la CDMX, que mantengan la consigna de no salir de casa y conservar la sana distancia, basada en la palabra, las historias, los relatos y las leyendas dirigida a infancias, juventudes, familias y personas de la tercera edad.  Se realizarán varias representaciones durante la jornada en la Unidad Habitacional.', 'Trayectoria de tres o más años en la narración oral y/o la lectura en voz alta Los temas de las propuestas serán libres y deben apegarse al principio de respeto de la diversidad y no discriminación. El repertorio debe ser su autoría o del dominio público. Contar con los instrumentos y elementos necesarios para ejecutar tu propuesta Facilidad para trasladarse y transportar el equipamiento necesario', 1, 1, NULL, NULL),
(4, 'Música', 'Cantante (mujer u hombre)', 50, 'Edificios que cantan Presentaciones musicales de 20 a 30 minutos, de reportorio académico, popular o tradicional de canto, los cuales tendrán lugar entre edificios contiguos de Unidades Habitacionales de la CDMX.  Los y las cantantes se ubicarán en ventanas, balcones o terrazas, previo acuerdo con los vecinos, cantando de un edificio a otro, guardando todas las medidas de sana distancia.  Se realizarán varias representaciones de la narración durante la jornada en la Unidad Habitacional.  ', 'Trayectoria de tres o más años en el medio del canto.   Los temas de las propuestas son libres y deben apegarse al principio de respeto y no discriminación.  La presentación es unipersonal a capela o acompañado de un instrumento   El repertorio debe ser de su autoría o del dominio público en los siguientes géneros: ópera, hip hop, jazz, blues, versada tradicional y/o fusión.   Contar con los instrumentos y elementos necesarios para ejecutar tu propuesta  Facilidad para trasladarse y transportar el equipamiento necesario', 1, 1, NULL, NULL),
(5, 'Teatral', 'Productor(a) escénico', 10, 'Coordinará y será responsable de la producción y adecuada realización de las actividades culturales en Unidades Habitacionales de la CDMX: desde la planeación y montaje hasta el desmontaje de estas, salvaguardando el cumplimiento de las medidas sanitarias pertinentes.  ', 'Trayectoria de tres o más años en producción de actividades en vivo y al aire libre de teatro, música y danza. Facilidad para trasladarse y para transportar el equipamiento técnico. Experiencia en manejo de público y control de masas. Capacidad de trabajo bajo presión y en equipo Conocimiento en la realización de riders y contrariders. Llevar su propio equipo de herramientas básicas.', 1, 1, NULL, NULL),
(6, 'Ingeniería de audio', 'Ingeniero(a) de audio', 10, 'Será responsable de sonorización de las actividades culturales en Unidades Habitacionales de la CDMX: desde la planeación, traslado y montaje del equipo, cableado a la cabina, soluciones técnicas durante la jornada hasta el desmontaje al término de la jornada; salvaguardando el cumplimiento de las medidas sanitarias pertinentes.  ', 'Trayectoria de cuatro o más años en sonorización de actividades en vivo y al aire libre de teatro, música y danza.  Facilidad para trasladarse y para transportar el equipamiento técnico. Experiencia en manejo de público y control de masas. Capacidad de trabajo bajo presión y en equipo Conocimiento en la realización de riders y contrariders. Contar con equipamiento básico de audio propio:  • Consola (12, 24 o más canales)   • Sistema estéreo con subwoofer (L, R y Sub).  • Computadora portátil con softwares para reproducir archivos de audio y video  • Reproductor de discos compactos   • Bocinas con medios, agudos y graves (1 bocina de cada lado) con tripie.  • Monitores de piso.  • Rack de amplificación.  • Micrófonos para voz   • Micrófonos lavalier o de diadema.  • Micrófonos inalámbricos.  • Micrófonos ambientales.  • Cajas directas   • Bases rectas para micrófono.  • Bases con boom para micrófono.  • Snake de 24CH con retornos. En caso de no contar con parte del equipamiento técnico para la actividad, el resto deberá de ser subarrendado por cuenta del/la ingeniero(a).', 1, 1, NULL, NULL),
(7, 'Artes visuales', 'Iluminador(a)', 10, 'Será responsable de la iluminación de las actividades culturales en Unidades Habitacionales de la CDMX: desde la planeación, traslado y montaje del equipo, cableado a la cabina, soluciones técnicas durante la jornada hasta el desmontaje al término de la jornada; salvaguardando el cumplimiento de las medidas sanitarias pertinentes.   ', 'Trayectoria de cuatro o más años en iluminación escénica en exterior de actividades en vivo y al aire libre de teatro, música y danza.  Facilidad para trasladarse y para transportar el equipamiento técnico.  Experiencia en manejo de público y control de masas.  Capacidad de trabajo bajo presión y en equipo  Conocimiento en la realización de riders y contrariders.  Realización rápida de diseños de iluminación para las actividades.  Contar con equipamiento del kit básico de iluminación propio:  • Controlador DMX.  • Beams 7r (cabezas móviles).   • Pares LED 36x3.  • Bases trípode para colocar 6 lámparas Par LED.  • Kits de cableado y accesorios necesarios para su funcionamiento.  En caso de contar con parte del equipamiento técnico, el resto deberá de ser subarrendado por el/la iluminador(a).', 1, 1, NULL, NULL),
(8, 'Artes visuales', 'Camarógrafos(as)', 10, 'Realizará el registro videográfico de actividades culturales en Unidades Habitacionales de la CDMX: desde el montaje hasta el desmontaje de las mismas.   Edición, subtitulaje y entrega del material audiovisual  Realizará las correcciones pertinentes que se indiquen a los materiales solicitados en tiempo y forma de acuerdo con las fechas de entrega que se indiquen.', 'Facilidad para trasladarse y transportar el equipamiento técnico  Experiencia mínima de 3 años en registro videográfico y postproducción de video.  Contar con equipo básico de video propio:   Cámara de video profesional  micrófonos ambientales para videocámara   Kit de cableados  Tripié para videocámara  Flash  Grabadora   Equipo de cómputo con softwares de edición de video   En caso de no contar con equipo propio este debe ser subarrendado por el/la fotógrafo(a)  Los productos audiovisuales serán utilizados por la Secretaría de Cultura del Gobierno de México para todos los contenidos que se requiera y considere pertinente.  Se deberá firmar una carta de cesión de derechos para la publicación y manipulación de las imágenes de los productos visuales que se entreguen.', 1, 1, NULL, NULL),
(9, 'Teatral, dancística, musical', 'Productora de artes escénicas', 10, 'Colaborar en las acciones de planificación y coordinación de recursos técnicos y humanos de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición de 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la producción de espectáculos de artes escénicas.\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, resolución expedita y eficiente de crisis, y manejo de paquetería de Office (Word, Excel, Power Point).\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(10, 'Teatral, dancística, musical', 'Productor de artes escénicas', 10, 'Colaborar en las acciones de planificación y coordinación de recursos técnicos y humanos de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición de 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la producción de espectáculos de artes escénicas.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, resolución expedita y eficiente de crisis, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(11, 'Audiovisual', 'Camarógrafo(a)', 10, 'Realizar grabaciones de video de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición de 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la videograbación de espectáculos de artes escénicas.\r\nLiderazgo, puntualidad, seguimiento de rutas críticas y manejo del software del propio equipo.\r\nContar con equipo propio que cumpla con las siguientes características mínimas: cámara Cannon C300 con 3 lentes de alta resolución, (18 mm, 50 mm y 24-85 mm), tripie, grabadora-mezcladora de sonido ambiental y kit básico de 2 parrillas de luces led.\r', 2, 1, NULL, NULL),
(12, 'Teatral, dancística, musical', 'Escenógrafa iluminadora', 10, 'Realizar el diseño espacial y lumínico de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a partir de un rider previamente configurado a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la realización de diseño espacial y lumínico de espectáculos de artes escénicas.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, capacidad de resolución de problemas con mínimos recursos.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(13, 'Teatral, dancística, musical', 'Escenógrafo iluminador', 10, 'Realizar el diseño espacial y lumínico de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a partir de un rider previamente configurado a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la realización de diseño espacial y lumínico de espectáculos de artes escénicas.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, capacidad de resolución de problemas con mínimos recursos.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(14, 'Teatral, dancística, musical', 'Diseñadora de vestuario', 10, 'Realizar el diseño de vestuario de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a partir de los elementos que los creadores tengan en casa, a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición de 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la realización de diseño de vestuario de espectáculos de artes escénicas.\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, capacidad de resolución de problemas con mínimos recursos.\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(15, 'Teatral, dancística, musical', 'Diseñador de vestuario', 10, 'Realizar el diseño de vestuario de diferentes espectáculos breves (de entre 5 y 8 minutos) de teatro, danza, circo y música a partir de los elementos que los creadores tengan en casa, a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición de 10 horas en un mismo espacio escénico.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en la realización de diseño de vestuario de espectáculos de artes escénicas.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, capacidad de resolución de problemas con mínimos recursos.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(16, 'Teatral', 'Actor de teatro', 170, 'Coadyuvar en los procesos de concepción, ensayo, producción y exhibición de una pieza teatral breve (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV  en el campo de la actuación.\nLiderazgo, puntualidad, habilidad para trabajar en equipo, mnemotecnia, comunicación asertiva, control y seguimiento de rutas críticas.\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(17, 'Teatral', 'Actriz de teatro', 170, 'Coadyuvar en los procesos de concepción, ensayo, producción y exhibición de una pieza teatral breve (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV  en el campo de la actuación.\r\nLiderazgo, puntualidad, habilidad para trabajar en equipo, mnemotecnia, comunicación asertiva, control y seguimiento de rutas críticas.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(18, 'Circense', 'Clown y/o artista circense mujer', 30, 'Colaborar en los procesos de concepción, ensayo, producción y exhibición de una pieza circense breve (de entre 5 y 8 minutos) de diferentes formatos y géneros (clown, malabarismo, equilibrismo , etc.) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de las artes circenses.\r\nDominio técnico de su disciplina, puntualidad, habilidad para trabajar en equipo, capacidad creativa de improvisación, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\r\nIndispensable contar con las herramientas propias de su disciplina. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(19, 'Circense', 'Clown y/o artista circense hombre', 30, 'Colaborar en los procesos de concepción, ensayo, producción y exhibición de una pieza circense breve (de entre 5 y 8 minutos) de diferentes formatos y géneros (clown, malabarismo, equilibrismo , etc.) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de las artes circenses.\nDominio técnico de su disciplina, puntualidad, habilidad para trabajar en equipo, capacidad creativa de improvisación, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\nIndispensable contar con las herramientas propias de su disciplina. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(20, 'Teatral', 'Titiritera', 20, 'Colaborar en los procesos de concepción, ensayo, producción y exhibición mediante el lenguaje del teatro de títeres de una pieza breve (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo del teatro de títeres.\r\nDominio técnico de su disciplina, puntualidad, habilidad para trabajar en equipo, capacidad creativa de improvisación, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\r\nIndispensable contar con títeres  u objetos ya realizados. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(21, 'Teatral', 'Titiritero', 20, 'Colaborar en los procesos de concepción, ensayo, producción y exhibición mediante el lenguaje del teatro de títeres de una pieza breve (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo del teatro de títeres.\r\nDominio técnico de su disciplina, puntualidad, habilidad para trabajar en equipo, capacidad creativa de improvisación, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\r\nIndispensable contar con títeres  u objetos ya realizados. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(22, 'Dancística', 'Bailarinas', 60, 'Colaborar y participar en los procesos de concepción, ensayo, producción y ejecución de una pieza de danza breve (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición, de diferentes formatos y géneros (clásico, contemporáneo, folclore, etc.).', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la danza.\r\nDominio técnico de su disciplina, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(23, 'Dancística', 'Bailarines', 60, 'Colaborar y participar en los procesos de concepción, ensayo, producción y ejecución de una pieza de danza breve (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de exhibición, de diferentes formatos y géneros (clásico, contemporáneo, folclore, etc.).', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la danza.\r\nDominio técnico de su disciplina, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(24, 'Teatral', 'Directora de escena', 20, 'Coordinar los procesos de concepción, ensayo, producción y exhibición de una pieza de varias piezas teatrales breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sóla jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la dirección escénica.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(25, 'Teatral', 'Director de escena', 20, 'Coordinar los procesos de concepción, ensayo, producción y exhibición de una pieza de varias piezas teatrales breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sóla jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la dirección escénica.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(26, 'Dancística', 'Coreógrafa', 20, 'Coordinar los procesos de concepción, ensayo, producción y exhibición de una pieza de varias piezas coreográficas breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sola jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la dirección coreográfica.\r\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(27, 'Dancística', 'Coreógrafo', 20, 'Coordinar los procesos de concepción, ensayo, producción y exhibición de una pieza de varias piezas coreográficas breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (realismo, farsa, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sola jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo de la dirección coreográfica.\nLiderazgo, comunicación asertiva, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\n', 2, 1, NULL, NULL),
(28, 'Teatral', 'Dramaturga', 20, 'Participar en los procesos de concepción y escritura de 2 a 3 piezas dramatúrgicas breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (teatro, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sola jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo  de la dramaturgia.\r\nHabilidades para la comunicación escrita, capacidad de síntesis y desarrollo expedito de textos breves, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(29, 'Teatral', 'Dramaturgo', 20, 'Participar en los procesos de concepción y escritura de 2 a 3 piezas dramatúrgicas breves (de entre 5 y 8 minutos) de diferentes formatos y géneros (teatro, teatro para primera infancia, niñas, niños y jóvenes audiencias, cabaret, performance, interdisciplinar, etc.) a lo largo de sesiones de preparación en línea y una sola jornada presencial de exhibición.', '3 años cumplidos de experiencia profesional comprobable por medio de CV en el campo  de la dramaturgia.\r\nHabilidades para la comunicación escrita, capacidad de síntesis y desarrollo expedito de textos breves, control y seguimiento de rutas críticas, y manejo de paquetería de Office (Word, Excel, Power Point).\r\nContar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\r', 2, 1, NULL, NULL),
(30, 'Musical', 'Músicas y/o cantantes mujeres', 45, 'Colaborar y participar en los procesos de concepción, ensayo, producción y ejecución de piezas musicales (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de presentación.', '3 años cumplidos de experiencia profesional en el campo de la música.\nDominio técnico de su disciplina, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\nIndispensable contar con su propio instrumento (salvo en el caso de pianos) y equipo de sonido necesario. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.\n', 2, 1, NULL, NULL),
(31, 'Musical', 'Músicos y/o cantantes hombres', 45, 'Colaborar y participar en los procesos de concepción, ensayo, producción y ejecución de piezas musicales (de entre 5 y 8 minutos) a lo largo de sesiones de preparación en línea y una jornada presencial de presentación.', '3 años cumplidos de experiencia profesional en el campo de la música.\nDominio técnico de su disciplina, liderazgo, comunicación asertiva, control y seguimiento de rutas críticas.\nIndispensable contar con su propio instrumento (salvo en el caso de pianos) y equipo de sonido necesario. Contar con teléfono celular propio para recibir notificaciones por correo electrónico y WhatsApp, así como equipo de cómputo e internet para coordinar sesiones de trabajo virtuales.', 2, 1, NULL, NULL),
(32, 'Artes visuales', 'Curador/a', 3, 'Seleccionar la obra y elaborar el texto introductorio, además de contenidos curatoriales en general.', 'Experiencia de 3 años en proyectos expositivos, conceptualización de proyectos y selección de obra.\n Capacidad de trabajo en equipo. Capacidad de conceptualización de exhibiciones dirigidas a público en general y en espacios exteriores.\n Conocimiento en fotografía', 3, 1, NULL, NULL),
(33, 'Artes visuales', 'Diseñador/a para tratamiento fotográfico y preparación de archivos', 3, 'Diseñar y formar textos.\n Editar y adaptar las imágenes de los fotógrafos a formato final para su impresión.', 'Experiencia de 3 años en edición de fotografía y preparación de archivos para salida a producción, según la técnica. Conocimiento de formatos, perfil de color, resolución.', 3, 1, NULL, NULL),
(34, 'Artes visuales', 'Diseñador de identidad gráfica de la exposición', 3, 'Diseñar la propuesta de identidad gráfica y su aplicación a invitación digital, y diseñar las cédulas de textos.', 'Experiencia de 3 años en generación de identidad gráfica y textos para proyectos expositivos, diseño gráfico en exposiciones.', 3, 1, NULL, NULL),
(35, 'Artes visuales', 'Escritor/a, editor/a o corrector', 1, 'Editar el texto curatorial, las fichas técnicas, los créditos y demás textos necesarios para la exhibición.', 'Experiencia de 3 años en edición de textos para exposiciones dirigidos al público en general. Conocimiento de fotografía de naturaleza. \n Capacidad de revisión y corrección de fichas técnicas para piezas fotográficas.', 3, 1, NULL, NULL),
(36, 'Artes visuales', 'Fotógrafos/as o artistas visuales', 30, 'Entregar 1 archivo sobre la vida cotidiana de las familias y las relaciones humanas de nuestro país, a color o blanco y negro, libres de derechos para su exhibición y publicación en los medios que la Secretaría de Cultura decida citando el presente proyecto. \n Elaborar y entregar una semblanza personal, de trabajo y archivo con características especificadas en la convocatoria', 'Visualización de su obra dentro de una de una propuesta conceptual colectiva', 3, 1, NULL, NULL),
(37, 'Artes visuales', 'Fotógrafos/as o artistas visuales', 30, 'Entregar 1 archivo sobre conjuntos de edificios o complejos arquitectónico de México, de cualquier periodo o corriente (prehispánica, colonial, moderna, contemporánea, etc.), a color o blanco y negro, libres de derechos para su exhibición y publicación en los medios que la Secretaría de Cultura decida citando el presente proyecto. \n Elaborar y entregar una semblanza personal, de trabajo y el archivo con las características especificadas en la convocatoria.', 'Visualización de su obra dentro de una de una propuesta conceptual colectiva', 3, 1, NULL, NULL),
(38, 'Artes visuales', 'Fotógrafos/as o atistas visuales', 30, 'Entregar 1 archivo de naturaleza (flora y fauna) retratada en México, con énfasis en especies endémicas y ecosistemas nativos de nuestro país, a color o blanco y negro, libre de derechos para su exhibición y publicación en los medios que la Secretaría de Cultura decida citando el presente proyecto. \n Elaborar y entregar una semblanza personal, de trabajo y archivo con las características especificadas en la convocatoria.', 'Visualización de su obra dentro de una de una propuesta conceptual colectiva', 3, 1, NULL, NULL),
(39, 'Artes visuales', 'Líder de proyecto (perfil de coordinador, museógrafo, diseñador)', 3, 'Fungir como el enlace con el Centro de la Imagen.\n Coordinar y organizar el equipo de trabajo.\n Llevar el cronograma de trabajo. \n Ruta crítica.\n Dar seguimiento y entregar la producción de todas las áreas. \n Coordinar el traslado de obra y mobiliario a los espacios expositivos. \n Coordinar el montaje e instalación de la exposición.\n Revisar las conexiones o instalaciones eléctricas cercanas. \n Al término de la exposición, coordinar el desmontaje, embalaje y traslado de obra y mobiliario.', 'Persona con 3 años de experiencia en la planeación, producción y montaje de exposiciones. \n Perfiles sugeridos: Project manager, coordinador de proyectos, museógrafo, diseñador. \n Capacidad de coordinación de un equipo de trabajo y organización de todas las áreas involucradas. \n Conceptualización y resolución del proyecto en su totalidad\n Manejo impecable de los tiempos de trabajo de cada elemento. Conocimiento de las actividades, etapas y procesos a desarrollarse durante todo el proceso del proyecto expositivo.', 3, 1, NULL, NULL),
(40, 'Artes visuales', 'Montajistas o ensambladores de mobiliario museográfico', 12, 'Realizar el montaje, desmontaje y embalaje de obra, traslado y movimiento de imrpesiones, mobiliario, herramienta y limpieza del espacio. Apoyar en lo que necesite la cadena logística del presente proyecto.', 'Persona con 3 años de experiencia en manipulación, montaje/desmontaje y embalaje de mobiliario museográfico y obra artística. Conocimiento de materiales y herramientas de montaje y embalaje, manipulación de obra y mobiliario, conocimiento de herramientas, electricidad.', 3, 1, NULL, NULL),
(41, 'Artes visuales', 'Editor/a', 1, 'Realizar la edición de la publicación electrónica del presente proyecto bajo las directrices dadas por el Centro de la Imagen/Secretaría de Cultura', 'Persona con - por lo menos - 3 años de experiencia en la edición de publicaciones culturales y de proyectos expositivos de manera física y digital', 3, 1, NULL, NULL),
(42, 'Artes visuales/Edición', 'Diseñador/a editorial', 1, 'Diseñar una publicación electrónica del presente proyecto bajo las directrices dadas por el Centro de la Imagen/Secretaría de Cultura, usando elementos y aplicaciones de la identidad gráfica de los proyectos expositivos', 'Persona con por lo menos 3 años de experiencia en el diseño editorial en e publicaciones culturales y de proyectos expositivos de manera física y digital', 3, 1, NULL, NULL),
(43, 'Artes visuales', 'Mediador/a', 1, 'Diseñar actividades de mediación para público en general para su desarrollo en la publicación del presente proyecto', 'Persona con por lo menos 3 años de experiencia en la mediación de contenidos expositivos o editoriales', 3, 1, NULL, NULL),
(44, 'Artes visuales/literatura', 'Escritores/as', 2, 'Escribir los textos sobre el presente proyecto para la publicación, y la integración de los contenidos producidos para el proyecto expositivo', 'Personas con por lo menos 3 años de experiencia en la escritura de textos para publicaciones físicas o digitales de proyectos culturales o expositivos', 3, 1, NULL, NULL),
(45, 'Artes visuales', 'Artistas visuales (fotográfos, pintores, ilustradores, diseñadores gráficos).', 33, 'Diseño de póster, diseño de pegatinas, intervención de bardas con un mural o grafiti. Se trabajará sobre los siguientes  temas:  mujeres trabajadoras, personas mayores, semillas que nos dieron patria, trabajadores de la construcción que expresen la diversidad cultural de sus lugares de origen y su lugar de trabajo, comunidades indígenas migrantes en la CDMX.', 'Con un mínimo de participación en 2 exposiciones colectivas. Deberá entregar los archivos de los diseños y  la cesión de derechos correspondiente.\n', 4, 1, NULL, NULL),
(46, 'Literatura', 'Poetas', 34, 'Trabajo en conjunto con artistas visuales para la generación de un conjunto de 3 poemas breves a partir de una imagen. \nSe trabajará sobre los siguientes  temas:  mujeres trabajadoras, personas mayores, semillas que nos dieron patria, trabajadores de la construcción que expresen la diversidad cultural de sus lugares de origen y su lugar de trabajo, comunidades indígenas migrantes en la CDMX.', 'Contar por lo menos con un libro publicado o una participación en una antología publicada. Se entregará un conjunto de 3 poemas y la cesión correspondiente de derechos de autor. \n', 4, 1, NULL, NULL),
(47, '', 'Artistas audiovisuales (fotografos, cineastas)', 16, 'Grabación durante 2 días de las intervenciones artísticas en calles.', 'El material se deberá entregar editado.', 4, 1, NULL, NULL),
(48, 'Radio', 'Actor', 7, 'Dar voz a los personajes, incluyendo secundarios o incidentales.', '', 5, 1, NULL, NULL),
(49, 'Radio', 'Actriz', 3, 'Dar voz a los personajes, incluyendo secundarios o incidentales.', '', 5, 1, NULL, NULL),
(50, 'Radio', 'Artista visual', 1, 'Diseñar visualmente a por lo menos dos personajes de la serie.', '', 5, 1, NULL, NULL),
(51, 'Radio', 'Asistente', 7, 'Realizar tareas de apoyo a la producción.', 'Debe contar con experiencia previa en asistencia radiofónica.', 5, 1, NULL, NULL),
(52, 'Radio', 'Conductor/a', 1, 'Dar voz a la narración radiofónica y entrevistar a invitados.', 'Se preferirá a músicos/as  con conocimientos generales sobre la historia de la música.', 5, 1, NULL, NULL),
(53, 'Radio', 'Conductor/a ', 2, 'Realizar entrevistas y dar voz al narrador.', '', 5, 1, NULL, NULL),
(54, 'Radio', 'Coordinador/a de entrevistas', 1, 'Seleccionar a los expertos que participarán en programa sobre algún tema de historia de la música que se le indicará y coordinar logística para entrevistas.', 'Se preferirá a músicos/as con conocimientos generales sobre la historia de la música', 5, 1, NULL, NULL),
(55, 'Radio', 'Coordinador/a de entrevistas', 1, 'Coordinar logística para entrevistas para un programa.', '', 5, 1, NULL, NULL),
(56, 'Radio', 'Director/a de escena', 2, 'Dirigir y supervisar la dramatización para grabación de un programa.', '', 5, 1, NULL, NULL),
(57, 'Radio', 'Diseñador/a gráfico', 1, 'Crear y desarrollar 7 logotipos y 7 anuncios o carteles para promocionar en redes sociales producciones radiofónicas.', 'Debe contar con paquetería y equipo propio. Firmar permiso de uso del material. ', 5, 1, NULL, NULL),
(58, 'Radio', 'Efectista', 2, 'Sugerir, buscar y generar efectos sonoros para vestir producción.', '', 5, 1, NULL, NULL),
(59, 'Radio', 'Guionista', 6, 'Elaborar diversos guiones de duración variada con base en la información que se le entregue por el investigador.', 'Firmar licencia de derechos para su reproducción.', 5, 1, NULL, NULL),
(60, 'Radio', 'Guionista', 1, 'Elaborar los guiones a partir de alguna obra literaria.', 'Firmar licencia de derechos para su reproducción.', 5, 1, NULL, NULL),
(61, 'Radio', 'Ingeniero/a de audio', 7, 'Diseñar audio y realizar edición de un programa.', 'Experiencia en el manejo de pro tools. Debe contar con equipo y software para trabajar a distancia.', 5, 1, NULL, NULL),
(62, 'Radio', 'Investigador/a', 5, 'Buscar información en fuentes especializadas. Apoyar al guionista en sus requerimientos de información.', '', 5, 1, NULL, NULL),
(63, 'Radio', 'Investigador/a ', 1, 'Buscar información en fuentes especializadas sobre determinado tema. Apoyar al guionista en sus requerimientos de información.', 'Se preferirá a un músico mujer u hombre.', 5, 1, NULL, NULL),
(64, 'Radio', 'Locutor/a', 3, 'Dar voz a narración radiofónica y entrevistar a invitados de un programa.', '', 5, 1, NULL, NULL),
(65, 'Radio', 'Locutor/a', 2, 'Dar voz a narración.', 'Se requieren voces jóvenes.', 5, 1, NULL, NULL),
(66, 'Radio', 'Musicalizador/a', 7, 'Seleccionar la música de librerías musicales libres de derechos o generar música original.', 'Se preferirá a músicos que puedan aportar composiciones originales.', 5, 1, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
